nvl_pib_origen <- tibble::tribble(
  ~orden, ~rae,
  '1',	'Agropecuario',
  '1.1',	'Subsector Agricola',
  '1.2',	'Ganader\\u00EDa, Silvicultura y Pesca',
  '1',	'Industrias',
  '1.1',	'Explotaci\\u00F3n de Minas y Canteras',
  '1.2',	'Manufactura Local',
  '1.2.1',	'Industrias de Alimentos',
  '1.2.2',	'Elaboraci\\u00F3n de Bebidas y Productos de Tabaco',
  '1.2.3',	'Fabricaci\\u00F3n de Productos de la Refinaci\\u00F3n de Petr\\u00F3leo y Quimicos',
  '1.2.4',	'Otras Manufacturas',
  '1.3',	'Manufactura Zonas Francas',
  '1.4',	'Construcci\\u00F3n',
  '1',	'Servicios',
  '1.1',	'Energ\\u00EDa y Agua',
  '1.2',	'Comercio',
  '1.3',	'Hoteles, Bares y Restaurantes',
  '1.4',	'Transporte y Almacenamiento',
  '1.5',	'Comunicaciones',
  '1.6',	'Intermediaci\\u00F3n Financiera, Seguros y Actividades Conexas',
  '1.7',	'Actividades Inmobiliarias y de Alquiler',
  '1.8',	'Ense\\u00F1anza',
  '1.8.1',	'Ense\\u00F1anza de Mercado',
  '1.8.2',	'Ense\\u00F1anza No de Mercado',
  '1.9',	'Salud',
  '1.9.1',	'Salud de Mercado',
  '1.9.2',	'Salud No de Mercado',
  '1.11',	'Otras Actividades de Servicios de Mercado',
  '1.12',	'Administraci\\u00F3n P\\u00FAblica y Defensa; Seguridad Social de Afiliaci\\u00F3n Obligatoria y Otros Servicios',
  '0',	'Valor Agregado',
  '0',	'Impuestos a la producci\\u00F3n netos de subsidios',
  '0',	'Producto Interno Bruto'
) %>%
  nivelador()

usethis::use_data(nvl_pib_origen, overwrite = TRUE)
