nvl_importaciones <- tibble::tribble(
  ~orden,	~detalle,
  '1',	'1.  Bienes de Consumo',
  '1.0.1',	'Bienes de consumo duradero (autom\\u00F3viles, electrodom\\u00E9sticos y otros)',
  '1.0.2',	'Partes o piezas de bienes de consumo',
  '1.0.3',	'Herramientas',
  '1.0.4',	'Repuestos para veh\\u00EDculos',
  '1.0.5',	'Estufas de gas y el\\u00E9ctricas',
  '1.0.6',	'Productos alimenticios elaborados o semielaborados (incl. aceites veg. refinados)',
  '1.0.7',	'Leche de todas clases',
  '1.0.8',	'Arroz para consumo',
  '1.0.9',	'Az\\u00FAcar refinada',
  '1.0.11',	'Productos medicinales y farmac\\u00E9uticos',
  '1.0.12',	'Productos blancos derivados de petr\\u00F3leo (combustibles)',
  '1.0.13',	'Otros combustibles elaborados',
  '1.0.14',	'Otros bienes de consumo',
  '2',	'2.  Materias Primas',
  '2.1',	'2.1 Nacionales',
  '2.1.1',	'Para la agricultura',
  '2.1.2',	'Para la industria alimenticia (sin elaborar)',
  '2.1.3',	'Aceites vegetales alimenticios (brutos o v\\u00EDrgenes)',
  '2.1.4',	'Ma\\u00EDz a granel p/moler (p/prep. alimentos animales y cosumo humano)',
  '2.1.5',	'Az\\u00FAcar cruda (parda)',
  '2.1.6',	'Madera',
  '2.1.7',	'Para la industria textil',
  '2.1.8',	'Para la industria de envases',
  '2.1.9',	'Para la industria de bebidas',
  '2.1.11',	'Tabaco sin elaborar',
  '2.1.12',	'Trigo a granel',
  '2.1.13',	'Petr\\u00F3leo crudo y reconstituido  (combustible)',
  '2.1.14',	'Otros combustibles sin elaborar',
  '2.1.15',	'Carb\\u00F3n mineral',
  '2.1.16',	'Grasas y aceites animales y vegetales (los dem\\u00E1s)',
  '2.1.17',	'Productos qu\\u00EDmicos inorg\\u00E1nicos',
  '2.1.18',	'Productos qu\\u00EDmicos org\\u00E1nicos',
  '2.1.19',	'Materias pl\\u00E1sticas artificiales',
  '2.1.21',	'Papel y cart\\u00F3n mfct. p/celulosa',
  '2.1.22',	'Fundici\\u00F3n de hierro y acero',
  '2.1.23',	'Otras materias primas y/o insumos intermedios',
  '2.2',	'2.2 Zonas Francas',
  '2.2.1',	'Materias primas',
  '2.2.2',	'Comercializadoras',
  '3',	'3.  Bienes de Capital',
  '3.1',	'3.1 Nacionales',
  '3.1.1',	'Para la agricultura',
  '3.1.2',	'Para la construcci\\u00F3n',
  '3.1.3',	'Para el transporte',
  '3.1.4',	'Para la industria',
  '3.1.5',	'Repuestos p/maquinarias y aptos.',
  '3.1.6',	'Otros bienes de capital',
  '3.2',	'3.2 Zonas Francas',
  '4',	'Total (1+2+3)',
  '4.1.1',	'Nacionales',
  '4.1.2',	'Zonas Francas',
  '4.2.1',	'Importaciones Petroleras 1/',
  '4.2.2',	'Importaciones No Petroleras 2/'
) %>%
  nivelador()

usethis::use_data(nvl_importaciones, overwrite = TRUE)
