nvl_idsevr <- tibble::tribble(
  ~orden, ~variable,
  "1", "Precios Combustibles",
  "1.1", "Fuel Oil # 2 (US$/BBL)",
  "1.2", "Fuel Oil # 2 (US$/MMBTU)",
  "1.3", "Fuel Oil # 6 (US$/BBL)",
  "1.4", "Fuel Oil # 6 (US$/MMBTU)",
  "1.5", "Gas Natural (US$/MMBTU)",
  "1.6", "Gas Natural Conversion (US$/MMBTU)",
  "1.7", "Carb\\u00F3n Mineral (US$/Ton)",
  "1.8", "Carb\\u00F3n Mineral (US$/MMBTU)",
  "2", "Generaci\\u00F3n de Energ\\u00EDa por tipo de combustible",
  "2.1", "Total Generaci\\u00F3n",
  "2.1.1", "Carb\\u00F3n Mineral",
  "2.1.2", "Gas Natural",
  "2.1.3", "Fuel Oil No. 2",
  "2.1.4", "Fuel Oil No. 6",
  "2.1.5", "Fuel Oil No. 2 y No. 6",
  "2.1.6", "Hidr\\u00E1ulica",
  "2.1.7.1", "Eòlica",
  "2.1.7.2", "Solar Fotovoltaica",
  "2.1.7.3", "Biomasa",
  "2.1.7", "Total Renovable No Convencional",
  "3", "Composici\\u00F3n Generaci\\u00F3n de Energ\\u00EDa por tipo de Combustible",
  "3.1", "Carb\\u00F3n Mineral",
  "3.2", "Gas Natural",
  "3.3", "Fuel Oil No. 2",
  "3.4", "Fuel Oil No. 6",
  "3.5", "Fuel Oil No. 2 y No. 6",
  "3.6", "Hidr\\u00E1ulica",
  "3.7.1", "Eòlica",
  "3.7.2", "Solar Fotovoltaica",
  "3.7.3", "Biomasa",
  "3.7", "Total Renovable No Convencional",
  "4", "Precios del Mercado El\\u00E9ctrico Mayorista (MEM)",
  "4.1", "Costos Marginal de Energ\\u00EDa (USCents$/KWh)",
  "4.2", "Costos Marginal de Potencia  (US$/kW-Mes)",
  "4.3", "Peaje de Transmisi\\u00F3n (USCents$/KWh)",
  "4.4", "Derecho de Conexi\\u00F3n Unitario (US$/kW-mes)",
  "5", "Tasa de Cambio  (RD$/US$)"
) %>% nivelador()

usethis::use_data(nvl_idsevr, overwrite = TRUE)
