nvl_indicadores_monetarios_bcrd <- tibble::tribble(
  ~orden, ~indicadores,
  '1',	"ACTIVOS INTERNACIONALES BRUTOS (Activos Externos) (US$) (1)",
  "1",	"RESERVAS INTERNACIONALES BRUTAS (Activos de Reserva Oficial) (US$) (1)",
  "1",	"RESERVAS INTERNACIONALES NETAS   (US$) (1)",
  "1",	"ACTIVOS INTERNOS",
  "1.1",	"Activos frente al Gobierno Central (2)",
  "1.1.1", "De los cuales: Bono de Capitalización (3)",
  "1.2",	"Activos frente al Sector Privado (4)",
  "1.3",	"Crédito a Otras Sociedades de Depósito (5)",
  "1",	"VALORES EN CIRCULACION (6)",
  "1.1",	"Descuento en Valores Emitidos",
  "1",	"DEPOSITOS REMUNERADOS DE CORTO PLAZO",
  "1",	"BASE MONETARIA RESTRINGIDA",
  "1.1",	"Billetes y Monedas Emitidos",
  "1.1.1",	"De los que: Tenencias OSD en MN",
  "1.2",	"Depósitos Encaje Legal y Saldos de Compensación de OSD en BC (MN)",
  "1.3",	"Valores del BCRD en posesión de las OSD para fines de encaje legal (MN)",
  "1",	"BASE MONETARIA AMPLIADA",
  "1.1",	"Base Monetaria Restringida",
  "1.2",	"Depósitos Encaje Legal y Saldos de Compensación de OSD en BC (ME)",
  "1.3",	"Depósitos Remunerados de Corto Plazo (Overnight)",
  "1.4",	"Depósitos Remunerados de Corto Plazo en ME",
  "1.5",	"Otros Depósitos de OSD en BCRD",
  "1.6",	"Valores a Corto Plazo emitidos por BC en manos de las OSD (MN y ME)",
  "1",	"MEDIO CIRCULANTE (M1)",
  "1.1",	"Billetes y monedas en poder del público",
  "1.2",	"Depósitos Transferibles en MN",
  "1",	"OFERTA MONETARIA AMPLIADA (M2)",
  "1.1",	"Medio Circulante (M1)",
  "1.2",	"Otros depósitos M/N",
  "1.3",	"Valores distintos de acciones MN-emitidos por OSD",
  "1.4",	"Valores distintos de acciones MN- emitidos por el BCRD",
  "1",	"DINERO EN SENTIDO AMPLIO (M3)",
  "1.1",	"Oferta Monetaria Ampliada (M2)",
  "1.2",	"Otros depósitos M/E",
  "1.3",	"Valores distintos de acciones ME",
  "1",	"K2.1 = M1/BM restringida",
  "1",	"K2.2 = M2/BM restringida",
  "1",	"K2.3 = M3/BM ampliada",
  "1", 	"TASA DE CAMBIO"
) %>%
  nivelador()

usethis::use_data(nvl_indicadores_monetarios_bcrd, overwrite = TRUE)
