nvl_exportaciones <- tibble::tribble(
  ~orden,	~detalle,
  '1',	 '1. Minerales',
  '1.0.1',	 'Oro',
  '1.0.2',	 'Ferroníquel',
  '1.0.3',	 'Cobre',
  '1.0.4',	 'Plata',
  '1.0.5',	 'Bauxita',
  '1.0.6',	 'Piedra caliza',
  '1.0.7',	 'Zinc',
  '1.0.8',	 'Otros minerales',
  '2',	 '2. Agropecuarios',
  '2.1',	'2.1 Nacionales',
  '2.1.1',	 'Guineos',
  '2.1.2',	 'Cacao en grano',
  '2.1.3',	 'Aguacates',
  '2.1.4',	 'Ajíes y pimientos',
  '2.1.5',	 'Cocos secos',
  '2.1.6',	 'Café en grano',
  '2.1.7',	 'Batata',
  '2.1.8',	 'Plátanos',
  '2.1.9',	 'Tabaco en rama',
  '2.1.11',	 'Otros agropecuarios',
  '2.2',	'2.2 Zonas Francas',
  '2.2.1',	 'Cacao en grano',
  '2.2.2',	 'Otros agropecuarios',
  '3',	 '3. Industriales',
  '3.1',	'3.1 Nacionales',
  '3.1.1',	 'Azúcar crudo y derivados',
  '3.1.2',	 'Productos de la industria química',
  '3.1.3',	 'Cemento gris',
  '3.1.4',	 'Varillas de acero',
  '3.1.5',	 'Ron de caña',
  '3.1.6',	 'Envases y tapas plásticos',
  '3.1.7',	 'Harina de trigo',
  '3.1.8',	 'Sazonadores y condimentos prep.',
  '3.1.9',	 'Galletas',
  '3.1.11',	 'Cervezas',
  '3.1.12',	 'Pastas alimenticias',
  '3.1.13',	 'Cajas de cartón corrugado',
  '3.1.14',	 'Frutas procesadas',
  '3.1.15',	 'Tabaco manufacturado',
  '3.1.16',	 'Café manufacturado',
  '3.1.17',	 'Cacao Manufacturado',
  '3.1.18',	 'Aceite de soya',
  '3.1.19',	 'Combustibles derivados del petróleo',
  '3.1.21',	 'Alimentos para aeronaves',
  '3.1.22',	 'Combustibles para aeronaves',
  '3.1.23',	 'Otros industriales',
  '3.2',	'3.2 Zonas Francas',
  '3.2.1',	 'Confecciones textiles',
  '3.2.2',	 'Productos eléctricos',
  '3.2.3',	 'Artículos de joyería y conexos',
  '3.2.4',	 'Productos farmacéuticos 2/',
  '3.2.5',	 'Fabricación equipos médicos y quirúrgicos 2/',
  '3.2.6',	 'Manufacturas de calzados',
  '3.2.7',	 'Manufacturas de tabaco',
  '3.2.8',	 'Cacao manufacturado',
  '3.2.9',	 'Alimentos para aeronaves',
  '3.2.11',	 'Otros industriales',
  '4',	 'Total  ( 1+2+3 )',
  '4.1',	 'Nacionales',
  '4.2',	 'Zonas Francas',
  '4.3',	 'Bienes Adquiridos en Puerto',
  '4.3.1',	 'Combustibles para aeronaves',
  '4.3.2',	 'Alimentos para aeronaves'
) %>%
  nivelador()

usethis::use_data(nvl_exportaciones, overwrite = TRUE)
