nvl_indicadores_osd <- tibble::tribble(
  ~orden, ~indicador,
  "1", "ACTIVOS EXTERNOS (US$) (9)",
  "1.1", "Bancos Múltiples",
  "1.2", "Resto OSD",
  "2", "PASIVOS EXTERNOS (US$) (9)",
  "2.1", "Bancos Múltiples",
  "2.2", "Resto OSD",
  "3", "INVERSIONES EN VALORES DISTINTOS DE ACCIONES (8)",
  "3.1", "Bancos Múltiples",
  "3.2", "Resto OSD",
  "4", "TOTAL DE PRÉSTAMOS (2), (8)",
  "4.0.1", "De los cuales: En M/N",
  "4.0.1.1", "Bancos Múltiples",
  "4.0.1.2", "Resto OSD",
  "4.0.2", "En US$ (1)",
  "4.0.2.1", "Bancos Múltiples",
  "4.0.2.2", "Resto OSD",
  "4.1", "SECTOR PÚBLICO",
  "4.1.1", "De los cuales: En M/N",
  "4.1.1.1", "Bancos Múltiples",
  "4.1.1.2", "Resto OSD",
  "4.1.2", "En US$ (1)",
  "4.1.2.1", "Bancos Múltiples",
  "4.1.2.2", "Resto OSD",
  "4.2", "SECTOR PRIVADO ",
  "4.2.1", "De los cuales: En M/N",
  "4.2.1.1", "Bancos Múltiples",
  "4.2.1.2", "Resto OSD",
  "4.2.2", "En US$ (1)",
  "4.2.2.1", "Bancos Múltiples",
  "4.2.2.2", "Resto OSD",
  "4.3", "SOCIEDADES FINANCIERAS",
  "4.3.1", "De los cuales: En M/N",
  "4.3.2", "En US$ (1)",
  "4.4", "NO RESIDENTES",
  "4.4.1", "De los cuales: En M/N",
  "4.4.2", "En US$ (1)",
  "5", "TOTAL DEPÓSITOS Y VALORES DISTINTOS DE ACCIONES (3), (7), (8)",
  "5.0.1", "De los cuales: En M/N",
  "5.0.1.1", "Bancos Múltiples",
  "5.0.1.2", "Resto OSD",
  "5.0.2", "En US$ (1)",
  "5.0.2.1", "Bancos Múltiples",
  "5.0.2.2", "Resto OSD",
  "5.1", "SECTOR PÚBLICO",
  "5.1.1", "De los cuales: En M/N",
  "5.1.1.1", "Bancos Múltiples",
  "5.1.1.2", "Resto OSD",
  "5.1.2", "En US$ (1)",
  "5.1.2.1", "Bancos Múltiples",
  "5.1.2.2", "Resto OSD",
  "5.2", "SECTOR PRIVADO ",
  "5.2.1", "De los cuales: En M/N",
  "5.2.1.1", "Bancos Múltiples",
  "5.2.1.2", "Resto OSD",
  "5.2.2", "En US$ (1)",
  "5.2.2.1", "Bancos Múltiples",
  "5.2.2.2", "Resto OSD",
  "5.3", "SOCIEDADES FINANCIERAS",
  "5.3.1", "De los cuales: En M/N",
  "5.3.2", "En US$ (1)",
  "5.4", "NO RESIDENTES",
  "5.4.1", "De los cuales: En M/N",
  "5.4.2", "En US$ (1)",
  "6", "TOTAL DEPÓSITOS Y VALORES DISTINTOS DE ACCIONES",
  "6.1", "Depósitos Transferibles",
  "6.2", "Otros Depósitos (de Ahorro No Transferibles y Depósitos a Plazo)",
  "6.3", "Valores Distintos de Acciones",
  "7", "TASA DE CAMBIO"
) %>%
  nivelador()

usethis::use_data(nvl_indicadores_osd, overwrite = TRUE)
