---
title: "Development"
output: 
  rmarkdown::html_vignette:
    toc: yes
vignette: >
  %\VignetteIndexEntry{Development}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


Una vez que has instalado el paquete y puedes ver estas vi\\u00F1etas, tu sistema cumple con los requisitos para contribuir con el desarrollo del paquete.

## Requisitos extras

Existe un API donde se encuentras un listado de todos los indicadores disponibles en el sistema. Es importante que tengas acceso a este listado para poder proceder con el desarrollo del paquete.

<!-- For contributing to the development the first thing that you need is to have access to the [domar file](https://docs.google.com/spreadsheets/d/1svANACeWShYC--wm7wwSKaUn_bF_xXuF81SnV8yMeb8/edit#gid=0), where can be find and set information about the indicators. -->

<!-- > If you have the access, don't change the file structure unless you know what do you do. -->

Para crear un indicador nuevo es importante que te tomes el tiempo de llenar todos los campos que te sean posibles en la tabla.

## Metodolog\\u00EDa

A pesar de que no es obligatorio, es altamente recomendado seguir la metolog\\u00EDa presentada en [R Packages](https://r-pkgs.org/) de Hadley Wickham, para le desarrollo del paquete.

## Flujo de trabajo

### Funciones base

#### downloader()

Utilizaras esta funci\\u00F3n en la definici\\u00F3n de las funciones de los indicadores. Vea la documentaci\\u00F3n de la funci\\u00F3n `downloader` para conocer como funciona.

Si la funci\\u00F3n `downloader` no cumple con sus requerimiento proponga una versi\\u00F3n modificada de dicha funci\\u00F3n al equipo de manera que se garantice que sigue funcionando para todas las dem\\u00E1s funciones.

#### to_date()

Esta funci\\u00F3n combina varias columnas relativas a fecha en una \\u00FAnica columna.

Es altamente recomendado que verifiques que la funci\\u00F3n `to_date` cumple con los requisitos necesarios para el indicador en el que est\\u00E1s trabajando. De lo contrario, inicia una discusi\\u00F3n con el equipo de desarrolladores acerca de una alternativa para la funci\\u00F3n.

Vea la documentaci\\u00F3n de la funci\\u00F3n `to_date` para ver como funciona.

#### domar_list()

Esta funci\\u00F3n obtiene la lista de indicadores en el sistema, donde se dispone de todos los p\\u00E1rametros relativos al indicador, necesarios para el desarrollo y funcionamiento del mismo.

Vea la documentaci\\u00F3n de la funci\\u00F3n `domar_list`.

#### gsheet_storage()

La funci\\u00F3n `gsheet_storage`  almacena los datos devueltos por las funciones de los indicadores en el Google Sheet indicado en la lista de indicadores.

Vea la documentaci\\u00F3n de la funci\\u00F3n `gsheet_storage` para detalles adicionales.

#### secure_gss()

Esta funci\\u00F3n es un `tryCatch` para la funci\\u00F3n `gsheet_storage`. Si ocurriese alg\\u00FAn error entonces un email es enviado al correo del desarrollador responsable de dicho indicador.

Vea la documentaci\\u00F3n de `secure_gss`.

### Nuevos indicadores

Para agregar un nuevo indicador:

- Completa el registro del indicador en la lista de indicadores del API.
  - Selecciona el ID cuidadosamente, the ID del indicador va a jugar un papel estelar en todo el proceso de desarrollo y     despliegue del indicador.
- El nombre de la funci\\u00F3n del indicador debe ser exactamente igual que el ID del indicador.
- Especifica las `kvars` de cada indicador, en la secci\\u00F3n `details` de la documentaci\\u00F3n de dicho indicador.
  - Las `kvars` son variables que las funciones `*_storage` utilizan para validar los datos.
  - Las primeras `n-1` kvars se utilizan como variables clave de los datos que identifican de manera \\u00FAnica a cada registro.
  - La \\u00FAltima kvar es una variable num\\u00E9rica que se utiliza para comparar los valores actuales con los nuevos en busca de consistencia.
  
Si est\\u00E1s trabajando en un indicador es importante que lo indiques en el campo correspondiente de la lista de indicadores, a fin de evitar la duplicaci\\u00F3n de esfuerzos.

#### Destination file

They are a Google Drive directory ([domar](https://drive.google.com/drive/u/0/folders/1HLbwqX4NgAVnXjchut9roCC6Zn6mH3Xb))
where are storage the Google Sheets tha contain the domar data exported by `gsheet_storage` function. It's irrelevant the name given to this files, but it's hightly recommended to use the indicator `id` in the domar list file as the file name, this way it's easy find aditional information for the content of the file.

This file need to be created with the following features:

- `Metadata` sheet: a sheet where to write all the relevant information about the indicator.
- `id` sheet: a sheet with the indicator id as name where `gsheet_storage` function will to write the data.

In the domar list put a direct url to the file in the `Metadata` field. Besides publish to the web the `id` sheet and put the public url in the domar list in the `Datos` field.
